[{
    "club":"energy",
    "eventName":"Robo war",
    "eventDetails":"In this ",
    "eventCo1":"X",
    "eventCo2":"Y",
    "eventCo3":"Z",
    "eventCo4":"A",
    "eventCo1No":"1",
    "eventCo2No":"2",
    "eventCo3No":"3",
    "eventCo4No":"4",
    "ruleBook":"",
    "whatsappGroup":"",
    "sponsor":""
},
{
    "club":"energy",
    "eventName":"Robo war",
    "eventDetails":"blah blah",
    "eventCo1":"X",
    "eventCo2":"Y",
    "eventCo3":"Z",
    "eventCo4":"A",
    "eventCo1No":"1",
    "eventCo2No":"2",
    "eventCo3No":"3",
    "eventCo4No":"4",
    "ruleBook":"",
    "whatsappGroup":"",
    "sponsor":""
},
{
    "club":"energy",
    "eventName":"Robo war",
    "eventDetails":"blah blah",
    "eventCo1":"X",
    "eventCo2":"Y",
    "eventCo3":"Z",
    "eventCo4":"A",
    "eventCo1No":"1",
    "eventCo2No":"2",
    "eventCo3No":"3",
    "eventCo4No":"4",
    "ruleBook":"",
    "whatsappGroup":"",
    "sponsor":""
}
]